<?php $_bannerslide = $this->getCollection(); ?>
<?php if ($_bannerslide->getSize()): ?>
<div class="bannerslide_list_view">
    <?php foreach ($_bannerslide as $bannerslideItem): ?>
        <div id="item_<?php echo $bannerslideItem->getId() ?>" class="bannerslide_list_item">
            <h2>
                <a href="<?php echo $this->getItemUrl($bannerslideItem) ?>">
                    <?php echo $this->escapeHtml($bannerslideItem->getTitle()) ?>
                </a>
            </h2>

            <div class="bannerslide_item_subtitle">
                <?php echo $this->formatDate($bannerslideItem->getPublishedAt()) ?> |
                <?php echo $this->escapeHtml($bannerslideItem->getAuthor()) ?>
            </div>

            <?php if ($imageUrl = $this->getImageUrl($bannerslideItem, 100)): ?>
               <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($bannerslideItem->getTitle()); ?>" /></p>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
<?php echo $this->getPager() ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('You have no Bannerslide.'); ?></span></div>
<?php endif ?>
