<?php
/**
 * Bannerslide template for separate item
 *
 */

/**
 * @var $this Embitel\Bannerslide\Block\View
 * @see Embitel\Bannerslide\Block\View
 */
?>
<?php $_bannerslideItem = $this->getBannerslide(); ?>
    <div class="bannerslide_item_subtitle">
        <?php echo $this->formatDate($_bannerslideItem->getPublishedAt()) ?> |
        <?php echo $this->escapeHtml($_bannerslideItem->getAuthor()) ?>
    </div>

<div class="bannerslide_item_view">
    <?php if ($imageUrl = $this->getImageUrl($_bannerslideItem, 400)): ?>
       <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($_bannerslideItem->getTitle()) ?>" /></p>
    <?php endif; ?>

    <div class="bannerslide_item_content"><?php echo $_bannerslideItem->getContent() ?></div>

    <div class="pager">
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo __('Return to list') ?>
        </a>
    </div>
</div>