<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$om = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $om->get('\Magento\Store\Model\StoreManagerInterface');
$store_id = $storeManager->getStore()->getStoreId();
$_config = $this->helper('Sm\Emarket\Helper\Data');
$tabStyle = $_config->getProductDetail('tab_style');

$show_custom_tab = $_config->getProductDetail('show_custom_tab');
$custom_tab_name = $_config->getProductDetail('custom_tab_name');
$customtab_content = $_config->getProductDetail('customtab_content');
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="tab-theme <?php echo $tabStyle . '-style'?>" id="tab-product">
			<ul class="resp-tabs-list">
				<?php foreach ($detailedInfoGroup as $name):?>
					<?php
						$html = $layout->renderElement($name);
						if (!trim($html)) {
							continue;
						}
						$alias = $layout->getElementAlias($name);
						$label = $block->getChildData($alias, 'title');
					?>
					
					<li id="<?php /* @escapeNotVerified */ echo $alias; ?>"><?php  echo $label; ?></li>
					
				<?php endforeach;?>
				
				<?php if($show_custom_tab){?>
					<li class="customtab"><?php  echo $custom_tab_name; ?></li>
				<?php } ?>
				<?php if($store_id==2){?>
                <li id="company-details" class="resp-tab-item" aria-controls="tab_item-3" role="tab">COMPANY DETAILS</li>
                <li id="related-certificates" class="resp-tab-item" aria-controls="tab_item-3" role="tab">DELATED CERTIFICATES</li>
                <?php }?>
			</ul>
			
			<div class="resp-tabs-container">
				<?php foreach ($detailedInfoGroup as $name):?>
					<?php
						$html = $layout->renderElement($name);
						if (!trim($html)) {
							continue;
						}
					?>
					
					<div><?php  echo $html; ?></div>
					
				<?php endforeach;?>
				
				<?php if($show_custom_tab){?>
					<div class="customtab-content">
						<?php  
							echo $customtab_content; 
						?>
					</div>
				<?php } ?>
                
                <div class="resp-tab-content" aria-labelledby="tab_item-3">company details no content</div>
                <div class="resp-tab-content" aria-labelledby="tab_item-4">related certificates no content</div>
			</div>
        </div>

		<script type="text/javascript">
			require([
				'jquery',
				'easyResponsiveTabs'
			], function ($) {
				$('#tab-product').easyResponsiveTabs({
					type: '<?php echo $tabStyle;?>', //Types: default, vertical, accordion           
					width: 'auto', //auto or any width like 600px
					fit: true,   // 100% fit in a container
					activate: function(event) { // Callback function if tab is switched
						/* var $tab = $(this);
						var $info = $('#tabInfo');
						var $name = $('span', $info);

						$name.text($tab.text());

						$info.show(); */
					}
				});
				
				$(".product-info-main .reviews-actions .action.view").click(function() {
					$("#reviews").trigger( "click" );
					$('html, body').animate({
						scrollTop: $("#customer-reviews").offset().top
					}, 1000);
				});
				
				$(".product-info-main .reviews-actions .action.add").click(function() {
					$("#reviews").trigger( "click" );
					$('html, body').animate({
						scrollTop: $("#review-form").offset().top
					}, 1000);
				});

			});
		</script>
    </div>
<?php endif; ?>

