
   <?php
        
        // get product by id
$product = $block->getProductById(15);
 
// get product by sku
//$product = $block->getProductBySku('MT12');
 
echo $product->getEntityId() . '<br>';
echo $product->getName() . '<br>';
echo $product->getSKU() . '<br>';
echo $product->getPrice() . '<br>';
echo $product->getSpecialPrice() . '<br>';
echo $product->getTypeId() . '<br>';
echo $product->getProductUrl() . '<br>';