<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block-subscribe-footer">
	
		<div class="title_block">
			<h3><?php echo __('Signup for Newsletter') ?></h3>
			<p><?php echo __("We'll never share your email address with a third-party.") ?></p>
		</div>
	
	
    <form class="form subscribe"
		novalidate
		action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
		method="post"
		data-mage-init='{"validation": {"errorClass": "mage-error"}}'
		id="newsletter-validate-detail-footer">

		<div class="input-box">
			<input name="email" type="email" id="newsletter-footer" onfocus="if(this.value=='Your email address') this.value='';" onblur="if(this.value=='') this.value='Your email address';" value="Your email address" data-validate="{required:true, 'validate-email':true}"/>
		</div>

		<div class="action-button">
			<button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
				<span><?php  echo __('Subscribe') ?></span>
			</button>
		</div>
    </form>
    
</div>
