<?php
/*------------------------------------------------------------------------
# SM Filter Products - Version 1.0.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

use Magento\Framework\App\Action\Action;

?>

<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">!-->

<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_config = $this->helper('Sm\Emarket\Helper\Data');
$homeStyle = $_config->getThemeLayout('home_style');
$nb_column1 = (int)$this->_getConfig('nb_column1', 3);
$_nb_column1 = ($nb_column1 > 0 && $nb_column1 <=6 && $nb_column1 !== 5) ? 12/$nb_column1 : 3;
$nb_column2 = (int)$this->_getConfig('nb_column2', 3);
$_nb_column2 = ($nb_column2 > 0 && $nb_column2 <=6 && $nb_column2 !== 5) ? 12/$nb_column2 : 3;
$nb_column3 = (int)$this->_getConfig('nb_column3', 3);
$_nb_column3 = ($nb_column3 > 0 && $nb_column3 <=6 && $nb_column3 !== 5) ? 12/$nb_column3 : 4;
$nb_column4 = (int)$this->_getConfig('nb_column4', 2);
$_nb_column4 = ($nb_column4 > 0 && $nb_column4 <=6 && $nb_column4 !== 5) ? 12/$nb_column4 : 12;
$check_type = ($this->_getConfig('type_show') == 'slide') ? true : false;
$nb_rows = $this->_getConfig('nb_row', 1);
$nav=$this->_getConfig('nav') == 1?'true':'false';
$dots=$this->_getConfig('dots') == 1?'true':'false';

$_cls = (!$check_type) ? 'col-lg-'.$_nb_column1.' col-md-'.$_nb_column2.' col-sm-'.$_nb_column3.' col-xs-'.$_nb_column4.'' : '';

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php
	$viewMode = 'grid';
	$image = 'category_page_grid';
	$showDescription = false;
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	$showWishlist = true;
    $showCompare = true;
    $showCart = true;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
	$tag_id = "sm_filterproducts_".time().rand()."";
    ?>
 <div class="sm-filter-products">  

	<?php if (!empty($this->_getConfig('title_module'))){?>
	<div class="title-slider-mega">
		<h2><?php echo $this->_getConfig('title_module') ;?></h2>
	</div>
	<?php } ?>

    <div id="<?php echo $tag_id; ?>" class="products sm-bs-menu <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
		<?php $iterator = 1; ?>
        <div class="<?php echo $check_type ? ' owl-carousel ' : '';  ?> products list items product-items  filterproducts">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): 
			?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item '.$_cls.'">' : '</div><div class="item product product-item '.$_cls.'">' ?>
                <div class="product-item-info item-inner"  data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
					
                    <?php // Product Image ?>
                    <div class="box-image">
                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
                        </a>
                    </div>
                    <div class="product details product-item-details box-info">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <h2 class="product name product-item-name product-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </h2>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                       
                      
						
						
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</div>' : '' ?>
            <?php endforeach; ?>
        </div>
    </div>
</div>	
	<script type="text/javascript">
        require([
            'jquery'
			<?php if ($check_type) { ?> ,
			'owlcarousel'
			<?php } ?>
        ], function ($) {
			var $element = $('#<?php echo $tag_id ?>');
			<?php if ($check_type) { ?>
			$('.owl-carousel', $element).owlCarousel({
				loop:true,
				nav:true,
				dots: false,
				autoplay: false,
				autoplayHoverPause: true,
				responsive: {
					0: {
						items:<?php echo $nb_column4;?>
					},
					768: {
						items:<?php echo $nb_column3;?>
					},
					991: {
						items:<?php echo $nb_column2;?>
					},						
					1200: {
						items: <?php echo $nb_column1;?>
					}
				}
			});
			<?php } ?>
			
        });
    </script>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
