<?php
/*------------------------------------------------------------------------
# SM Filter Products - Version 1.0.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

use Magento\Framework\App\Action\Action;

?>

<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">!-->

<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_config = $this->helper('Sm\Emarket\Helper\Data');
$homeStyle = $_config->getThemeLayout('home_style');
$nb_column1 = (int)$this->_getConfig('nb_column1', 3);
$_nb_column1 = ($nb_column1 > 0 && $nb_column1 <=6 && $nb_column1 !== 5) ? 12/$nb_column1 : 3;
$nb_column2 = (int)$this->_getConfig('nb_column2', 3);
$_nb_column2 = ($nb_column2 > 0 && $nb_column2 <=6 && $nb_column2 !== 5) ? 12/$nb_column2 : 3;
$nb_column3 = (int)$this->_getConfig('nb_column3', 3);
$_nb_column3 = ($nb_column3 > 0 && $nb_column3 <=6 && $nb_column3 !== 5) ? 12/$nb_column3 : 4;
$nb_column4 = (int)$this->_getConfig('nb_column4', 2);
$_nb_column4 = ($nb_column4 > 0 && $nb_column4 <=6 && $nb_column4 !== 5) ? 12/$nb_column4 : 12;
$check_type = ($this->_getConfig('type_show') == 'slide') ? true : false;
$nb_rows = $this->_getConfig('nb_row', 1);
$nav=$this->_getConfig('nav') == 1?'true':'false';
$dots=$this->_getConfig('dots') == 1?'true':'false';

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php
	$viewMode = 'grid';
	$image = 'category_page_grid';
	$showDescription = false;
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	$showWishlist = true;
    $showCompare = true;
    $showCart = true;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
	$tag_id = "sm_filterproducts_".time().rand()."";
    ?>
<div class="products-sidebar block">
	<?php if (!empty($this->_getConfig('title_module'))){?>
		<div class="block-title filter-title">
			<strong><?php echo $this->_getConfig('title_module') ;?></strong>
		</div>
	<?php } ?>
    <div id="<?php echo $tag_id; ?>" class="products block-content">
        
		<?php
		if ($this->_getConfig('product_source') == 'countdown_products') { 
			$dateTo = $this->_getConfig('date_to', '');	
		?>
		<div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($dateTo)); ?>"></div>
		<?php }?>
		<?php $iterator = 0; ?>
        <div class="<?php echo $check_type ? ' owl-carousel ' : '';  ?> products list items product-items  filterproducts">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): 
			?>
                <?php if($iterator % $nb_rows==0)/* @escapeNotVerified */  echo '<div class="item product product-item ">' ?>
                <div class="product-item-info item-inner" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
					
                    <?php // Product Image ?>
	                <div class="box-image">
	                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
	                        <?php echo $productImage->toHtml(); ?>
	                    </a>
	                </div>
                    <div class="product details product-item-details box-info">
                    	 <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <h2 class="product name product-item-name product-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php  echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'),0,40).'...'; ?>
                            </a>
                        </h2>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                       
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                    </div>
                    <p class="clearfix"></p>
                </div>
              <?php $iterator++; if($iterator%$nb_rows==0 || $iterator == count($_productCollection))  echo '</div>' ?>
              
            <?php endforeach; ?>
        </div>
    </div>
</div>
	<script type="text/javascript">
        require([
            'jquery'
			<?php if ($check_type) { ?> ,
			'owlcarousel'
			<?php } ?>
        ], function ($) {
			var $element = $('#<?php echo $tag_id ?>');
			<?php if ($check_type) { ?>
			//alert(1)
			$('.owl-carousel', $element).owlCarousel({
				loop:false,
				nav:true,
				dots: false,
				margin:30,
				autoplay: false,
				autoplayHoverPause: true,
				items:1
			});
			<?php } ?>
			function CountDown(date,id){
				dateNow = new Date();
				amount = date.getTime() - dateNow.getTime();
				delete dateNow;
				if(amount < 0){
					id.html("Now!");
				} else{
					days=0;hours=0;mins=0;secs=0;out="";
					amount = Math.floor(amount/1000);
					days=Math.floor(amount/86400);
					amount=amount%86400;
					hours=Math.floor(amount/3600);
					amount=amount%3600;
					mins=Math.floor(amount/60);
					amount=amount%60;
					secs=Math.floor(amount);
					out += "<div class='deals-time time-day'><div class='num-time'>"+ days +"</div><div class='title-time'>"+((days==1)?"Day":"Days")+"</div></div>";
					out += "<div class='deals-time time-hours'><div class='num-time'>"+ hours +"</div><div class='title-time'>"+((hours==1)?"Hour":"Hours")+"</div></div>";
					out += "<div class='deals-time time-mins'><div class='num-time'>"+ mins +"</div><div class='title-time'>"+((mins==1)?"Min":"Mins")+"</div></div>";
					out += "<div class='deals-time time-secs'><div class='num-time'>"+ secs +"</div><div class='title-time'>"+((secs==1)?"Sec":"Secs")+"</div></div>";
					out = out.substr(0,out.length-2);
					id.html(out);
					setTimeout(function(){CountDown(date,id)}, 1000);
				}
			}
			$( ".deals-countdown",$element).each(function() {
				var timer = $(this).data('timer');
				var data = new Date(timer);
				CountDown(data,$(this));
			});
        });
    </script>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
