<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');       
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store_id = $storeManager->getStore()->getStoreId();
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */

$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');

$_config = $this->helper('Sm\Emarket\Helper\Data');

$related_limit = $_config->getProductDetail('related_limit');
$upsell_limit = $_config->getProductDetail('upsell_limit');

$show_addtocart = $_config->getAdvanced('show_addtocart_button');
$show_addtocompare = $_config->getAdvanced('show_compare_button');
$show_addtowishlist = $_config->getAdvanced('show_wishlist_button');

$show_newlabel = $_config->getAdvanced('show_newlabel');
$new_label_text = $_config->getAdvanced('new_label_text');

$show_salelabel = $_config->getAdvanced('show_salelabel');
$sale_label_text = $_config->getAdvanced('sale_label_text');
$show_pecent = $_config->getAdvanced('show_salediscount');

$homeStyle = $_config->getThemeLayout('home_style');

?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $hover_image = 'category_page_grid-hover';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $related_limit;
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $hover_image = 'category_page_grid-hover';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = $related_limit;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $hover_image = 'category_page_grid-hover';
            $title = __('Upsell Products');
            $items = $block->getAllItems();
            $limit = $upsell_limit;
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $hover_image = 'category_page_grid-hover';
            $title = __('Upsell Products');
            $items = $block->getItemCollection()->getItems();
            $limit = $upsell_limit;
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;
}
?>

<?php if ($exist):?>


<div class="block block-detail <?php /* @escapeNotVerified */ echo $class; ?>">
    
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
        <div class="products  products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
        	<a href="#" class="sp-owl" id="sp-prev"><img src="<?php echo $this->getViewFileUrl('images/owl-prev.png') ?>"></a>
            <a href="#" class="sp-owl" id="sp-next"><img src="<?php echo $this->getViewFileUrl('images/owl-next.png') ?>"></a>
            <div class="grid-product-type products list items product-items slider-products">
                <?php $i=0; foreach ($items as $_item): $i++; ?>
                <?php //echo "ss".$_item->getEntityId();?>
                <div class="item product product-item">
                <?php if($store_id == 2){ ?>
                	<div class="sp-wholeseller-item make-full-no-pad">
                               <div class="sp-inner-item">
                                  <div class="item-image">
                                     <div class="sp_assured_new"><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/Hallal-Assured-final.png"></div>
                                     <div class="wsale">
                                        <div class="wsale-inner">
                                           <a href="#"><img class="img" src="http://halalglobalhub.com/pub/static/version1517217035/frontend/Sm/emarket/en_US/images/whole.png"></a>
                                           <ul>
                                              <li>
                                                 <span class="price-container price-final_price tax weee">
                                                 <span class="price-label">As low as</span>
                                                 <span id="90" data-price-amount="44000" data-price-type="" class="price-wrapper ">
                                                 ₹1400.0000    </span>
                                                 </span>
                                              </li>
                                           </ul>
                                        </div>
                                     </div>
                                     <a title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="wholeseller-item-photo"><?= $block->getImage($_item, $image)->toHtml() ?></a>
                                  </div>
                                  <div class="sp-wholeseller-info">
                                     <h2 class="wholeseller-product-name">
                                        <a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>"><?= $block->escapeHtml($_item->getName()) ?></a>
                                     </h2>
                                     <div class="seller_name"><span>Seller / Company :</span> Halalhub</div>
                                     <div class="retail-price"><span>Retail Price :</span>₹1919</div>
                                     <div class="WholesalePrice">Wholesale Price</div>
                                     <div class="sp-wholeseller-price">
                                        <span class="price">₹1919</span>
                                     </div>
                                     <div class="moq-holder">
                                        <div class="moq">MOQ : 100</div>
                                        <a href="#" class="moq2">Custom Branding</a>
                                     </div>
                                     <input value="halalglobalhub@gmail.com" class="seller_id" type="hidden">
                                     <div class="sp-bottom-action">
                                        <div class="sp-top-section"><span>Types of seller:</span> Manufacture <span class="con-icon"><img class="img" src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/india.png"></span></div>
                                        <div class="sp-bottom-section">
                                           <div class="sp-3rating"><img class="img" src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/3star.png"></div>
                                           <div class="sp-transaction">Transaction Value</div>
                                           <div class="sp-mail"><a href="#" class="sendmail" data-toggle="modal" data-target="#contactModal"><img class="img" src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/wmail.png"></a></div>
                                           <div class="sp-com"><a class="action tocompare btn-action link-compare" title="Add to Compare" aria-label="Add to Compare" data-post="{&quot;action&quot;:&quot;http:\/\/halalglobalhub.com\/wholeseller\/catalog\/product_compare\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;6&quot;,&quot;uenc&quot;:&quot;aHR0cDovL2hhbGFsZ2xvYmFsaHViLmNvbS93aG9sZXNlbGxlci8,&quot;}}" role="button"><img class="img" src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/com-w.png"></a></div>
                                        </div>
                                     </div>
                                  </div>
                               </div>
                            </div>
                <?php }else{ ?>
                
                    <div class="item-inner <?php if ($homeStyle=='home-1') {echo 'style1';} ?>">
                       <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                            $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getEntityId());?>
                            <div class="box-image product-item-image">
                                <?php if($_product->getAttributeText('assured')=="Yes"){?>
                            	<div class="sp_assured_new"><img src="<?php echo $this->getViewFileUrl('images/Hallal-Assured-final.png') ?>"></div>
                                <?php }?>
                                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                    <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                </a>
                                <?php if ($homeStyle !='home-1') {?>
                                    <div class="bottom-action">
                                    
                                        <?php if($show_addtocart){ ?>
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <a class="action tocart primary  btn-action btn-cart"
                                                            data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </a>
                                                <?php else: ?>
                                                    <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <a class="action  btn-action tocart primary  btn-cart"
                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php } ?>
                                        
                                        <?php if($show_addtowishlist){ ?>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                   class="action towishlist btn-action link-wishlist" data-action="add-to-wishlist"
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php } ?>
                                        
                                        <?php if($show_addtocompare){ ?>
                                            <?php if ($block->getAddToCompareUrl()): ?>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                <a href="#" class="action tocompare btn-action link-compare"
                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php } ?>
                                    </div>
                                    <?php } ?>
                              
                                
                                <!--Label-->
                                <?php
                                if($show_newlabel) {
                                    $now = date("Y-m-d");
                                    $newsFrom= substr($_item->getData('news_from_date'),0,10);
                                    $newsTo=  substr($_item->getData('news_to_date'),0,10);
                                    
                                    if ($newsTo != '' || $newsFrom != ''){
                                        if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo)) {
                                            echo '<div class="product-label new-label">'.$new_label_text.'</div>';
                                        }
                                    }
                                }

                                if($show_salelabel) {
                                    $orgprice = $_item->getPrice();
                                    $specialprice = $_item->getSpecialPrice();
                                    $specialfromdate = $_item->getSpecialFromDate();
                                    $specialtodate = $_item->getSpecialToDate();
                                    $today = time();

                                    if(!$specialprice)
                                        $specialprice = $orgprice;
                                    
                                    if($specialprice < $orgprice) {
                                        if((is_null($specialfromdate) && is_null($specialtodate)) || ($today >= strtotime($specialfromdate) && is_null($specialtodate)) || ($today <= strtotime($specialtodate) && is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))){
                                            if($show_pecent) {
                                                $save_percent = 100-round(($specialprice/$orgprice)*100);
                                                echo '<div class="product-label sale-label">'.'-'.$save_percent.'%'.'</div>';
                                            } else {
                                                echo '<div class="product-label sale-label">'.$sale_label_text.'</div>';
                                            }
                                        }
                                    }   
                                }
                                ?>
                                <!--End label-->
                            </div>
                            
                            <div class="product details box-info product-item-details">
                                <div class="product name product-item-name product-name">
                                    <a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </div>
                                
                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>

                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                                <?php if ($homeStyle =='home-1') {?>
                                     <div class="bottom-action">
                                    
                                        <?php if($show_addtocart){ ?>
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <a class="action tocart primary  btn-cart"
                                                            data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </a>
                                                <?php else: ?>
                                                    <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <a class="action tocart primary  btn-cart"
                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php } ?>
                                        
                                        <?php if($show_addtowishlist){ ?>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                   class="action towishlist btn-action link-wishlist" data-action="add-to-wishlist"
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php } ?>
                                        
                                        <?php if($show_addtocompare){ ?>
                                            <?php if ($block->getAddToCompareUrl()): ?>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                <a href="#" class="action tocompare btn-action link-compare"
                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            
                            </div>
                      
                    </div>
                
                <?php } ?>
                </div>
                <?php if($i == $limit) break;?>
                <?php endforeach ?>
            </div>
        </div>
    </div>
</div>
<div id="other-section">
	<h2>Other Products of this seller</h2>
	<div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
        <div class="products  products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
        	<a href="#" class="sp-owl" id="sp-prev"><img src="<?php echo $this->getViewFileUrl('images/owl-prev.png') ?>"></a>
            <a href="#" class="sp-owl" id="sp-next"><img src="<?php echo $this->getViewFileUrl('images/owl-next.png') ?>"></a>
            <div class="grid-product-type products list items product-items slider-products">
                <?php $i=0; foreach ($items as $_item): $i++; ?>
                <?php //echo "ss".$_item->getEntityId();?>
                <div class="item product product-item">
                <?php if($store_id == 2){ ?>
                	<div class="sp-wholeseller-item make-full-no-pad">
                               <div class="sp-inner-item">
                                  <div class="item-image">
                                     <div class="sp_assured_new"><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/Hallal-Assured-final.png"></div>
                                     <div class="wsale">
                                        <div class="wsale-inner">
                                           <a href="#"><img class="img" src="http://halalglobalhub.com/pub/static/version1517217035/frontend/Sm/emarket/en_US/images/whole.png"></a>
                                           <ul>
                                              <li>
                                                 <span class="price-container price-final_price tax weee">
                                                 <span class="price-label">As low as</span>
                                                 <span id="90" data-price-amount="44000" data-price-type="" class="price-wrapper ">
                                                 ₹1400.0000    </span>
                                                 </span>
                                              </li>
                                           </ul>
                                        </div>
                                     </div>
                                     <a title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="wholeseller-item-photo"><?= $block->getImage($_item, $image)->toHtml() ?></a>
                                  </div>
                                  <div class="sp-wholeseller-info">
                                     <h2 class="wholeseller-product-name">
                                        <a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>"><?= $block->escapeHtml($_item->getName()) ?></a>
                                     </h2>
                                     <div class="seller_name"><span>Seller / Company :</span> Halalhub</div>
                                     <div class="retail-price"><span>Retail Price :</span>₹1919</div>
                                     <div class="WholesalePrice">Wholesale Price</div>
                                     <div class="sp-wholeseller-price">
                                        <span class="price">₹1919</span>
                                     </div>
                                     <div class="moq-holder">
                                        <div class="moq">MOQ : 100</div>
                                        <a href="#" class="moq2">Custom Branding</a>
                                     </div>
                                     <input value="halalglobalhub@gmail.com" class="seller_id" type="hidden">
                                     <div class="sp-bottom-action">
                                        <div class="sp-top-section"><span>Types of seller:</span> Manufacture <span class="con-icon"><img class="img" src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/india.png"></span></div>
                                        <div class="sp-bottom-section">
                                           <div class="sp-3rating"><img class="img" src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/3star.png"></div>
                                           <div class="sp-transaction">Transaction Value</div>
                                           <div class="sp-mail"><a href="#" class="sendmail" data-toggle="modal" data-target="#contactModal"><img class="img" src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/wmail.png"></a></div>
                                           <div class="sp-com"><a class="action tocompare btn-action link-compare" title="Add to Compare" aria-label="Add to Compare" data-post="{&quot;action&quot;:&quot;http:\/\/halalglobalhub.com\/wholeseller\/catalog\/product_compare\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;6&quot;,&quot;uenc&quot;:&quot;aHR0cDovL2hhbGFsZ2xvYmFsaHViLmNvbS93aG9sZXNlbGxlci8,&quot;}}" role="button"><img class="img" src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/com-w.png"></a></div>
                                        </div>
                                     </div>
                                  </div>
                               </div>
                            </div>
                <?php }else{ ?>
                
                    <div class="item-inner <?php if ($homeStyle=='home-1') {echo 'style1';} ?>">
                       <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                            $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getEntityId());?>
                            <div class="box-image product-item-image">
                                <?php if($_product->getAttributeText('assured')=="Yes"){?>
                            	<div class="sp_assured_new"><img src="<?php echo $this->getViewFileUrl('images/Hallal-Assured-final.png') ?>"></div>
                                <?php }?>
                                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                    <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                </a>
                                <?php if ($homeStyle !='home-1') {?>
                                    <div class="bottom-action">
                                    
                                        <?php if($show_addtocart){ ?>
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <a class="action tocart primary  btn-action btn-cart"
                                                            data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </a>
                                                <?php else: ?>
                                                    <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <a class="action  btn-action tocart primary  btn-cart"
                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php } ?>
                                        
                                        <?php if($show_addtowishlist){ ?>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                   class="action towishlist btn-action link-wishlist" data-action="add-to-wishlist"
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php } ?>
                                        
                                        <?php if($show_addtocompare){ ?>
                                            <?php if ($block->getAddToCompareUrl()): ?>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                <a href="#" class="action tocompare btn-action link-compare"
                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php } ?>
                                    </div>
                                    <?php } ?>
                              
                                
                                <!--Label-->
                                <?php
                                if($show_newlabel) {
                                    $now = date("Y-m-d");
                                    $newsFrom= substr($_item->getData('news_from_date'),0,10);
                                    $newsTo=  substr($_item->getData('news_to_date'),0,10);
                                    
                                    if ($newsTo != '' || $newsFrom != ''){
                                        if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo)) {
                                            echo '<div class="product-label new-label">'.$new_label_text.'</div>';
                                        }
                                    }
                                }

                                if($show_salelabel) {
                                    $orgprice = $_item->getPrice();
                                    $specialprice = $_item->getSpecialPrice();
                                    $specialfromdate = $_item->getSpecialFromDate();
                                    $specialtodate = $_item->getSpecialToDate();
                                    $today = time();

                                    if(!$specialprice)
                                        $specialprice = $orgprice;
                                    
                                    if($specialprice < $orgprice) {
                                        if((is_null($specialfromdate) && is_null($specialtodate)) || ($today >= strtotime($specialfromdate) && is_null($specialtodate)) || ($today <= strtotime($specialtodate) && is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))){
                                            if($show_pecent) {
                                                $save_percent = 100-round(($specialprice/$orgprice)*100);
                                                echo '<div class="product-label sale-label">'.'-'.$save_percent.'%'.'</div>';
                                            } else {
                                                echo '<div class="product-label sale-label">'.$sale_label_text.'</div>';
                                            }
                                        }
                                    }   
                                }
                                ?>
                                <!--End label-->
                            </div>
                            
                            <div class="product details box-info product-item-details">
                                <div class="product name product-item-name product-name">
                                    <a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </div>
                                
                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>

                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                                <?php if ($homeStyle =='home-1') {?>
                                     <div class="bottom-action">
                                    
                                        <?php if($show_addtocart){ ?>
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <a class="action tocart primary  btn-cart"
                                                            data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </a>
                                                <?php else: ?>
                                                    <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <a class="action tocart primary  btn-cart"
                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php } ?>
                                        
                                        <?php if($show_addtowishlist){ ?>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                   class="action towishlist btn-action link-wishlist" data-action="add-to-wishlist"
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php } ?>
                                        
                                        <?php if($show_addtocompare){ ?>
                                            <?php if ($block->getAddToCompareUrl()): ?>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                <a href="#" class="action tocompare btn-action link-compare"
                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            
                            </div>
                      
                    </div>
                
                <?php } ?>
                </div>
                <?php if($i == $limit) break;?>
                <?php endforeach ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'owlcarousel'
    ], function ($) {
		
        var owl_<?php echo $type;?> = $(".<?php echo $type;?> .slider-products");
        owl_<?php echo $type;?>.owlCarousel({
            
            responsive:{
                0:{
                    items:1
                },
                480:{
                    items:2
                },
                768:{
                    items:3
                },
                992:{
                    items:3
                },
                1200:{
                    items:5
                },
                1650:{
                    items:5
                }
            },

            autoplay:false,
            loop:false,
            nav : false, // Show next and prev buttons
            dots: false,
            autoplaySpeed : 500,
            navSpeed : 500,
            dotsSpeed : 500,
            autoplayHoverPause: true,
            margin:40,

        }); 
		$('.block-detail .products-grid.products-related .sp-owl#sp-prev').click(function(event) {
			event.preventDefault();
			owl_<?php echo $type;?>.trigger('prev.owl.carousel');
		})
		$('.block-detail .products-grid.products-related .sp-owl#sp-next').click(function(event) {
			event.preventDefault();
			owl_<?php echo $type;?>.trigger('next.owl.carousel');
		})
    }); 
</script>
<?php endif;?>
