<script>
var tvc_UA_ID = <?php echo json_encode($block->getUaId()); ?>;        
var tvc_cur = <?php echo json_encode($block->getLocalCurrency());?>;
var tvc_ver =  <?php echo json_encode($block->getMagentoVersion());?>;

var tvc_smd= {
	'tvc_UA_ID': tvc_UA_ID,
	'tvc_cur'  : tvc_cur,
	'tvc_version':tvc_ver,
};
(function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,"script","//www.google-analytics.com/analytics.js","ga");
    ga("create", tvc_UA_ID, "auto");
    ga("require", "ec", "ec.js");
    ga('set', 'currencyCode', tvc_cur);
    ga("send", "pageview");
	
</script>
<?php
	list($tvc_data,$get_action) = $block->getAction();

	if( $get_action == 'catalog_product_view') {
		echo"<script>
			var tvc_pp =".$tvc_data.";
			require(
					['Tatvic_EnhancedEcommerce/js/enhanced_ecommerce','jquery'], 
						function(enhanced_ecommerce){
							var obj = new enhanced_ecommerce();
							obj.tvc_pro_detail(tvc_pp);
							obj.tvc_add_to_cart(tvc_pp);
						}
			);
		</script>";	
	}
	if( $get_action == 'catalog_category_view') {
		echo"<script>
			var tvc_pgc =".$tvc_data.";
			require(
					['Tatvic_EnhancedEcommerce/js/enhanced_ecommerce','jquery'], 
						function(enhanced_ecommerce){
							var obj = new enhanced_ecommerce();
							obj.tvc_get_impression(tvc_pgc);
							obj.tvc_impr_click(tvc_pgc);
						}
			);
		</script>";
	}
	if( $get_action == 'checkout_cart_index') {
		echo"<script>
        var tvc_remove =".$tvc_data.";
        require(
                ['Tatvic_EnhancedEcommerce/js/enhanced_ecommerce','jquery'], 
                    function(enhanced_ecommerce){
                        var obj = new enhanced_ecommerce();
                        obj.tvc_remove_cart(tvc_remove);
                    }
        );
        </script>";
	}
	if( $get_action == 'checkout_onepage_success') {
		echo"<script>
		var tvc_oo =".$tvc_data.";
		var t_keys = Object.keys(tvc_oo);
		var t_last = t_keys[tvc_oo.length-1];
		require(
				['Tatvic_EnhancedEcommerce/js/enhanced_ecommerce','jquery'], 
					function(enhanced_ecommerce){
						var obj = new enhanced_ecommerce();
						obj.tvc_transaction_call(tvc_oo,tvc_oo[t_last]);
					}
		);
		</script>";
	}

?>
