<?php
/**
 *
 * SM Listing Tabs - Version 2.3.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */
 
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$catalog_ids1 = array();
$p=0;
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');       
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store_id = $storeManager->getStore()->getStoreId();
 $customerSession = $objectManager->get('Magento\Customer\Model\Session');
 if($customerSession->isLoggedIn()) {
//  $customgp = $customerSession->getCustomer()->getGroupId();
//  if($customgp==2){
     $p=1;
  }else{
    $p=0;
  }
// }else{
//    $p=0;
// }
?>
<?php
if ($this->_isAjax()) {
    $products = $this->_ajaxLoad();
}           
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_config = $this->helper('Sm\Emarket\Helper\Data');

$show_addtocompare = $_config->getAdvanced('show_compare_button');
$show_addtowishlist = $_config->getAdvanced('show_wishlist_button');
$show_newlabel = $_config->getAdvanced('show_newlabel');
$new_label_text = $_config->getAdvanced('new_label_text');
$show_salelabel = $_config->getAdvanced('show_salelabel');
$sale_label_text = $_config->getAdvanced('sale_label_text');
$show_pecent = $_config->getAdvanced('show_salediscount');
$homeStyle = $_config->getThemeLayout('home_style');
$viewMode = 'grid';
$image = 'category_page_grid';
$showDescription = false;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$type_loadmore = $this->_getConfig('type_show') == 'loadmore' ? true : false;
$cls_mark = $type_loadmore ? ' ltabs-mark ' : '';
    
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="new-style-sp new-style-small products list items product-items  <?php echo $type_loadmore == false ? ' owl-carousel ' : ''; ?>"  <?php echo $type_loadmore ?  'data-liffect="fadeIn"' : '' ;?>>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($products as $_product): 
            
            ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item '.$cls_mark.'">' : '</li><li class="item product product-item '.$cls_mark.'">' ?>
                	<div class="product-item-info item-inner" >
                       <div class="product product-item">
                          <div class="box-image">
                          	<?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                             	<?php if($_product->getAttributeText('assured')=="Yes"):?>
                                    <div class="sp_assured_new"><img src="<?php echo $this->getViewFileUrl('images/Hallal-Assured-final.png') ?>" ></div>
                                <?php endif;?>
                             <!--LABEL PRODUCT-->
                             <!--END LABEL PRODUCT-->
                             <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
                        	</a>
                          </div>
                          <div class="product details product-item-details box-info">
                             <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <h2 class="product name product-item-name product-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </h2>
                             <div class="sp-rating">
                                <?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
                                <!-- <div class="sp-review">256 reviews</div> -->
                             </div>
                             <div class="sp-product-price">
                                
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                
                                <!-- <div class="sp-orginal-price">2,090.00 <span>20% off</span></div> -->
                             </div>
                             <div class="bottom-action">
                             
                             		<?php if ($_product->isSaleable()){ ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <?php if($_product->getTypeId()=="configurable"){?>
                                             <a href="<?php echo $_product->getProductUrl()?>" class="confirmation"><img src="<?php echo $this->getViewFileUrl('images/s-cart.png') ?>"></a>
                                            <?php }else{?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart btn-action primary btn-cart">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                        <?php }?>
                                        <?php } ?>
                                        <?php if($show_addtowishlist){ ?>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                            <?php if($p==1){?>
                                                <a href="#"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                   class="action towishlist btn-action link-wishlist" data-action="add-to-wishlist"
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                                <?php }else{?>
                                                <a href="#" class="action towishlist btn-action notloginwishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"  aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" role="button">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                <?php }?>
                                            <?php endif; ?>
                                        <?php } ?>
                                        <?php if($show_addtocompare){ ?>
                                            <?php if ($block->getAddToCompareUrl()): ?>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                <a href="#" class="action tocompare btn-action link-compare"
                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product);?>'
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php } ?>
                                        
										
							 </div>
                          </div>
                       </div>
                    </div>
                <?php echo($iterator == count($products)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
        <div class="clearfix"></div>
    </div>
