<?php
/**
 *
 * SM Listing Tabs - Version 2.3.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */
 
$_cfg = json_encode($this->_getConfig());
$_cfg = strtr(rtrim(base64_encode($_cfg), '='), '+/', '-_');
?>
<script type="text/javascript">
 require(['jquery' , 'owlcarousel'], function ($) {
		;(function (element) {
		var el = $(element),
		tabs_wrap = $('.ltabs-tabs-wrap',el),
		tab = $('.ltabs-tab', el),
		tab_active = $('.ltabs-tab.tab-sel .ltabs-tab-label',tabs_wrap), 
		tab_content = $('.ltabs-items', el),
		ajax_url = $('.ltabs-tabs-container', el).attr('data-ajaxurl'),
		btn_loadmore = $('.ltabs-loadmore-btn', el),
		type_loadmore = <?php echo $this->_getConfig('type_show') == 'loadmore' ? 'true' : 'false'; ?>,
		place_holder_tab = $('.ltabs-current-select', el),
		nb_column4 = 1, nb_column3 = 2, nb_column2 = 3, nb_column1 = 5;
		var _interval = setInterval(function() {
		if(document.readyState === 'complete') {
			clearInterval(_interval);
				el.removeClass('ltabs-loading-first');
				_runAllScript();
			}    
		}, 500);
		function _runAllScript () {
			place_holder_tab.text(tab_active.text());
			tabs_wrap.on('click', function(e){
				e.preventDefault();
				var _that = $(this);
				_that.toggleClass('active');
				return false;		
			});
			tab.off('click').on('click', function (e) {
				e.preventDefault();
				var _self = $(this);
				if (_self.hasClass('tab-sel')) return false;
				tab.removeClass('tab-sel');
				_self.addClass('tab-sel');
				place_holder_tab.text($('.ltabs-tab-label', _self).text());
				var tab_id = _self.attr('data-tab-id'),
					catids = _self.attr('data-catids'),
					items_active = $('.ltabs-items-'+tab_id, el),
					loading = $('.ltabs-loading', items_active),
					loaded = items_active.hasClass('ltabs-items-loaded');
				tab_content.removeClass('ltabs-items-selected');
				items_active.addClass('ltabs-items-selected');
				
				if (!loaded && !items_active.hasClass('ltabs-process')) {
					items_active.addClass('ltabs-process');
					loading.show();
					$.ajax({
						type: 'POST',
						url: ajax_url,
						data: {
							is_ajax_listing_tabs: 1,
							ajax_listingtabs_start: 0,
							tab_id: tab_id,
							catids: catids,
							config: '<?php echo $_cfg; ?>'
						},
						success: function (data) {
							if (data.items_markup != '') {
								$('.ltabs-items-inner', items_active).html(data.items_markup);
								items_active.addClass('ltabs-items-loaded').removeClass('ltabs-process');
								if (type_loadmore){
									$('.product-item', items_active).removeAttr('style');
									$('.product-items', items_active).removeClass('play');
									$('.product-item', items_active).addClass('ltabs-mark');
									animatesItems(items_active);	
								}else{
									_runOwlCarousel(items_active);
								}
								$(document).trigger("afterAjaxProductsLoaded");
								loading.remove();
								updateStatus(items_active);
							}
						},
						dataType: 'json'
					});

				}else{
					if (type_loadmore){
						$('.product-item', items_active).removeAttr('style');
						$('.product-items', items_active).removeClass('play');
						$('.product-item', items_active).addClass('ltabs-mark');
						animatesItems(items_active);
					}else{
						var owl = $('.owl-carousel' , items_active);
						 owl = owl.data('owlCarousel');
						if (typeof owl !== 'undefined') 
							owl.onResize();
						else{
							_runOwlCarousel(items_active);
						}
						
					}
				}
			});
			
			btn_loadmore.off('click').on('click', function (e) {
				e.preventDefault();
				var _self = $(this);
				if (_self.hasClass('loaded') || _self.hasClass('loading')) {
					return false;
				} else {
					_self.addClass('loading');
					$('.ltabs-image-loading', _self).css({display: 'inline-block'});
					var rl_start = _self.parent().attr('data-rl_start'),
						catids = _self.parent().attr('data-catids'),
						tab_id = _self.parent().attr('data-tab-id'),
						items_active = $('.ltabs-items-'+tab_id, el);
					$.ajax({
						type: 'POST',
						url: ajax_url,
						data: {
							is_ajax_listing_tabs: 1,
							ajax_listingtabs_start: rl_start,
							tab_id: tab_id,
							catids: catids,
							config: '<?php echo $_cfg; ?>'
						},
						success: function (data) {
							if (data.items_markup != '') {
								$('.product-item',$(data.items_markup)).insertAfter($('.product-item:last-child', items_active));
								$('.ltabs-image-loading', _self).css({display: 'none'});
								animatesItems(items_active);
								updateStatus(items_active);
								$(document).trigger("afterAjaxProductsLoaded");
							}
						}, dataType: 'json'
					});
				}
				return false;
			});
				
			function animatesItems(elem){
					 var _item = $('.product-item.ltabs-mark', elem);
					_item.stop(true, true).each(function (i) {
						var newDelay = i * 200, 
						duration = 400;
						$(this).attr("style", "-webkit-animation-delay:" + newDelay + "ms; "
							+ "-moz-animation-delay:" + newDelay + "ms; "
							+ "-o-animation-delay:" + newDelay + "ms; "
							+ "animation-delay:" + newDelay + "ms; "
							+ "-webkit-animation-duration:" + duration + "ms;"
							+ "-moz-animation-duration:" + duration + "ms;"
							+ "-o-animation-duration:" + duration + "ms;"
							+ "animation-duration:" + duration + "ms;");
						if (i == _item.size()-1) {
							$('.product-items', elem).fadeIn(newDelay).addClass("play");
							$('.product-item', elem).removeClass('ltabs-mark');			
						}
					});
			}
			
			function updateStatus($el) {
				$('.ltabs-loadmore-btn', $el).removeClass('loading');
				var countitem = $('.product-item', $el).length;
				$('.ltabs-image-loading', $el).css({display: 'none'});
				$('.ltabs-loadmore-btn', $el).parent().attr('data-rl_start', countitem);
				var rl_total = $('.ltabs-loadmore-btn', $el).parent().attr('data-rl_total');
				var rl_load = $('.ltabs-loadmore-btn', $el).parent().attr('data-rl_load');
				var rl_allready = $('.ltabs-loadmore-btn', $el).parent().attr('data-rl_allready');
					
				if (countitem >= rl_total) {
					$('.ltabs-loadmore-btn', $el).addClass('loaded');
					$('.ltabs-image-loading', $el).css({display: 'none'});
					$('.ltabs-loadmore-btn', $el).attr('data-label', rl_allready);
					$('.ltabs-loadmore-btn', $el).removeClass('loading');
				}
				_displayCountDown($el);
			}
			
			function _countDown(date,id){
				dateNow = new Date();
				amount = date.getTime() - dateNow.getTime();
				delete dateNow;
				if(amount < 0){
					id.html("Now!");
				} else{
					days=0;hours=0;mins=0;secs=0;out="";
					amount = Math.floor(amount/1000);
					days=Math.floor(amount/86400);
					amount=amount%86400;
					hours=Math.floor(amount/3600);
					amount=amount%3600;
					mins=Math.floor(amount/60);
					amount=amount%60;
					secs=Math.floor(amount);
					out += "<div class='deals-time time-day'><div class='num-time'>"+ days +"</div><div class='title-time'>"+((days==1)?"Day":"Days")+"</div></div>";
					out += "<div class='deals-time time-hours'><div class='num-time'>"+ hours +"</div><div class='title-time'>"+((hours==1)?"Hour":"Hours")+"</div></div>";
					out += "<div class='deals-time time-mins'><div class='num-time'>"+ mins +"</div><div class='title-time'>"+((mins==1)?"Min":"Mins")+"</div></div>";
					out += "<div class='deals-time time-secs'><div class='num-time'>"+ secs +"</div><div class='title-time'>"+((secs==1)?"Sec":"Secs")+"</div></div>";
					out = out.substr(0,out.length-2);
					id.html(out);
					setTimeout(function(){_countDown(date,id)}, 1000);
				}
			}
			function _displayCountDown ($el){
				if ($( ".deals-countdown",$el).length){
					$( ".deals-countdown",$el).each(function() {
						var timer = $(this).data('timer');
						var data = new Date(timer);
						_countDown(data,$(this));
					});
				}
			}
			
			function _runOwlCarousel(el) {
				$('.owl-carousel', el).owlCarousel({
					loop:true,
					nav:true,
					dots: true,
					autoplay: false,
					autoplayHoverPause: true,
					responsive: {
						0: {
							items: nb_column4
						},
						768: {
							items: nb_column3
						},
						991: {
							items: nb_column2
						},						
						1200: {
							items: nb_column1
						}
					}
				});
			}
			if (type_loadmore){
				animatesItems($('.ltabs-items.ltabs-items-selected', el));
			}else{
				_runOwlCarousel($('.ltabs-items.ltabs-items-selected', el));
			}
			_displayCountDown($('.ltabs-items.ltabs-items-selected', el));	
		}
	})("#<?php echo $tag_id; ?>");	
 });
</script>