<?php
/**
 *
 * SM Listing Tabs - Version 2.3.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */
 
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
if ($this->_isAjax()) {
    $products = $this->_ajaxLoad();
}           
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_config = $this->helper('Sm\Emarket\Helper\Data');

$show_addtocompare = $_config->getAdvanced('show_compare_button');
$show_addtowishlist = $_config->getAdvanced('show_wishlist_button');
$show_newlabel = $_config->getAdvanced('show_newlabel');
$new_label_text = $_config->getAdvanced('new_label_text');
$show_salelabel = $_config->getAdvanced('show_salelabel');
$sale_label_text = $_config->getAdvanced('sale_label_text');
$show_pecent = $_config->getAdvanced('show_salediscount');
$viewMode = 'grid';
$image = 'category_page_grid';
$showDescription = false;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$type_loadmore = $this->_getConfig('type_show') == 'loadmore' ? true : false;
$cls_mark = $type_loadmore ? ' ltabs-mark ' : '';
    
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items  <?php echo $type_loadmore == false ? ' owl-carousel ' : ''; ?>"  <?php echo $type_loadmore ?  'data-liffect="fadeIn"' : '' ;?>>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($products as $_product): 
            
            ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item '.$cls_mark.'">' : '</li><li class="item product product-item '.$cls_mark.'">' ?>
                <div class="product-item-info  item-inner" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php
                    if ((int)$this->_getConfig('display_countdown') && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) { 
                        $specialToDate = $_product->getSpecialToDate();
                    ?>
                    <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>"></div>
                    <?php }?>
                    <?php // Product Image ?>
                    <div class="box-image dddd">
                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
                        </a>
                        <!--Label-->
                                <?php
                                if($show_newlabel) {
                                    $now = date("Y-m-d");
                                    $newsFrom= substr($_product->getData('news_from_date'),0,10);
                                    $newsTo=  substr($_product->getData('news_to_date'),0,10);
                                    
                                    if ($newsTo != '' || $newsFrom != ''){
                                        if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo)) {
                                            echo '<div class="product-label new-label">'.$new_label_text.'</div>';
                                        }
                                    }
                                }

                                if($show_salelabel) {
                                    $orgprice = $_product->getPrice();
                                    $specialprice = $_product->getSpecialPrice();
                                    $specialfromdate = $_product->getSpecialFromDate();
                                    $specialtodate = $_product->getSpecialToDate();
                                    $today = time();

                                    if(!$specialprice)
                                        $specialprice = $orgprice;
                                    
                                    if($specialprice < $orgprice) {
                                        if((is_null($specialfromdate) && is_null($specialtodate)) || ($today >= strtotime($specialfromdate) && is_null($specialtodate)) || ($today <= strtotime($specialtodate) && is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))){
                                            if($show_pecent) {
                                                $save_percent = 100-round(($specialprice/$orgprice)*100);
                                                echo '<div class="product-label sale-label">'.'-'.$save_percent.'%'.'</div>';
                                            } else {
                                                echo '<div class="product-label sale-label">'.$sale_label_text.'</div>';
                                            }
                                        }
                                    }   
                                }
                                ?>
                                <!--End label-->
                        
                    </div>
                    <div class="product details product-item-details box-info">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <h2 class="product name product-item-name product-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </h2>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                       class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                </div>
                        <?php endif; ?>
                        
                            <div class="product actions product-item-actions bottom-action"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                               <!--  <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>> -->
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary btn-cart">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                <!-- </div> -->
                                <?php if($show_addtowishlist){ ?>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                   class="action towishlist btn-action link-wishlist" data-action="add-to-wishlist"
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php } ?>
                                        
                                        <?php if($show_addtocompare){ ?>
                                            <?php if ($block->getAddToCompareUrl()): ?>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                <a href="#" class="action tocompare btn-action link-compare"
                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product);?>'
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php } ?>
                            </div>
                         
                        
                    </div>
                </div>
                <?php echo($iterator == count($products)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
        <div class="clearfix"></div>
    </div>
