<?php $welcomeMessage = $block->getWelcome(); ?>

<div class="header-container header-style-2">
	<div class="header-top">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-xs-6">
					<div class="customer-action-hd">
						<span class="welcome-text">

							<span class="greet welcome" data-bind="scope: 'customer'">
								<!-- ko if: customer().fullname  -->
								<span data-bind="text: new String('<?php echo $block->escapeHtml(__('Welcome, %1!', '%1'));?>').replace('%1', customer().firstname)">
								</span>
								<!-- /ko -->
								<!-- ko ifnot: customer().fullname  -->
								<span data-bind="html:'<?=$block->escapeHtml($welcomeMessage) ?>'"></span>
								<!-- /ko -->
							</span>
							<script type="text/x-magento-init">
							{
								"*": {
									"Magento_Ui/js/core/app": {
										"components": {
											"customer": {
												"component": "Magento_Customer/js/view/customer"
											}
										}
									}
								}
							}
							</script>

						</span>
						
						<?php
							$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
							$customerSession = $objectManager->get('Magento\Customer\Model\Session');
						?>
						
						<?php if($customerSession->isLoggedIn()){?>
							<a href="<?php echo $this->getUrl('customer/account/logout')?>" title="<?php echo __('Logout')?>"><?php echo __('Logout')?></a>
						<?php } else {?>
							<a href="<?php echo $this->getUrl('customer/account/create')?>" title="<?php echo __('Create Your Account')?>"><?php echo __('Join Free')?></a> <?php echo __('or')?> <a href="<?php echo $this->getUrl('customer/account/login')?>" title="<?php echo __('Sign In')?>"><?php echo __('Sign in')?></a>
						<?php } ?>
					</div>
				</div>
					
				<div class="col-md-6 col-xs-6 language-currency-top">
					<?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Theme::html/social.phtml')->toHtml(); ?>
					<?php echo $block->getChildHtml('language-header'); ?>
					<?php echo $block->getChildHtml('currency-header'); ?>
					
				</div>
			</div>
		</div>
	</div>
	<div class="header-middle">
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<?php echo $block->getChildHtml('logo-header'); ?>
				</div>
				<div class="col-sm-6 searchbox-header">
					<?php echo $block->getChildHtml('search-header-pro'); ?>
				</div>
				<div class="col-sm-3">
					<div class="compare-wishlist">
                            <a class="header-compare hidden-sm hidden-xs" href="<?php echo $block->getUrl('catalog/product_compare/index') ?>"><?php echo __('My Compare')?></a>
                        
                        <!-- COMPARE -->
          
                            <a class="header-wishlist hidden-xs" href="<?php echo $block->getUrl('wishlist') ?>"><?php echo __('My Wishlist')?></a>
                     
					</div>
				</div>
			</div>
		</div>
	</div>


	<div class="header-bottom">
		<div class="container">
			<div class="row">
				<div class="main-megamenu col-lg-8 col-md-8 col-xs-3">
					<?php echo $block->getChildHtml('navigation-header-megamenu'); ?>
					<div class="navigation-mobile-container">
						<?php echo $block->getChildHtml('navigation.mobile'); ?>
					</div>
				</div>
				
				<div class="col-lg-4 col-md-4 col-xs-9 ">
					<div class="minicart-header">
							<div class="minicart-content">
								<?php echo $block->getChildHtml('cart-header'); ?>
							</div>
					</div>


				</div>
			</div>
		</div>
	</div>
</div>
