<div id="siteDirectory">
  <!--[if IE]>
    <div class='nav-ie-min-width' style='width: 960px'></div>
  <![endif]-->
<?php
$ab = array();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$catId = 2; // Parent Category ID
$subcategory = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
$subcats = $subcategory->getChildrenCategories();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php
foreach ($subcats as $subcat) {
$_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
$_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
$subcaturl = $subcat->getUrl();
$_imgHtml = '';
if ($_imgUrl = $_category->getImageUrl()) {
$_imgHtml = '<img src="' . $_imgUrl . '" />';
$_imgHtml = $_outputhelper->categoryAttribute($_category, $_imgHtml, 'image');
/* @escapeNotVerified */

} ?>
<?php $ab[] = $subcat->getId(); ?>
<?php } ?>
<div id="shopAllLinks">
	<div class="grid">
    	<div class="grid-sizer"></div>
      <?php
      foreach($ab as $ab1){
$catId = $ab1; // Parent Category ID
$subcategory = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
$subcats = $subcategory->getChildrenCategories();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
if (count($subcats) > 0){
?>
     <div class="grid-item">
		<div class="item-block">
        	<div class="popover-grouping">
                   <h2 class="popover-category-name"><?php echo $subcategory->getName()?></h2>
                   <ul class="nav_cat_links">
                    <?php 
                    foreach ($subcats as $subcat) {
                    $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
                    $_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
                    $subcaturl = $subcat->getUrl();
                    ?>
                      <li class="nav_first"><a href="<?php echo $subcaturl ?>" class="nav_a"><?php echo $subcat->getName(); ?></a></li>
                      <?php }?>
                      <!-- <li class="nav_first"><a href="#" class="nav_a">Echo Dot</a></li>
                      <li class="nav_first"><a href="#" class="nav_a">Echo Dot</a></li>
                      <li class="nav_first"><a href="#" class="nav_a">Echo Dot</a></li>
                      <li class="nav_first"><a href="#" class="nav_a">Echo Dot</a></li>
                      <li class="nav_first"><a href="#" class="nav_a">Echo Dot</a></li> -->
                   </ul>
                </div>
        </div>
     </div>		
<?php }}?>
            

  </div>

</div>


<script type="text/javascript">
	/*require([
		'jquery',
		'masonry'
	], function ($) {
		alert(11);
		$('.grid').masonry({
			// options
			itemSelector: '.grid-item',
			//percentPosition: true,
			columnWidth: '.grid-sizer',
			//fitWidth: true,
			resize: true
		});  
	});*/
	require([
    'jquery',
    'domReady',
    'masonry',
], function ($, domReady, Masonry) {

    console.log("custom-masonry.js");

    domReady(function() {

        console.log("domReady");
        var elem = document.querySelector('.grid');
         var msnry = new Masonry( elem, {
               itemSelector: '.grid-item',
			//percentPosition: true,
			columnWidth: '.grid-sizer',
			//fitWidth: true,
			resize: true
         });

    });

});
</script>