<?php
$str_less = "
		body{
		  background-color: @body_background_color;
		  font-family: @body_font_family;
		  font-size: @body_font_size;
		  color: @text_color;
		  line-height: 1.66;
			background-image:url('@{background_path}');
			background-repeat: @background_repeat;
			background-position: @background_position;
		}

		.label{
		  color: @text_color;
		}

		a,
		a:focus,
		a:visited{
		  color: @link_color;
		}

		a:hover{
		  color: @link_hover_color;
		}

		/* GENERAL */
		.owl-controls .owl-nav div:hover,
		.page-title:before,
		button:hover,
		.cart-container .action.continue:hover,
		a.action.primary:hover
		{
		  background-color: @theme_color;
		}

		.fotorama__thumb-border{
			border-color: @theme_color!important;
		}

		.fotorama__active .fotorama__dot{
			border-color: @theme_color!important;
			background-color: @theme_color;
		}

		.cart-container .cart.table-wrapper .product-item-photo .product-image-photo:hover{
			border-color: @theme_color;
		}

		.cartpro-modal .cpmodal-button{
			background-color: @theme_color;
		}

		#btn-gallery:hover{
			background-color: @theme_color;
		}

		.owl-dots .owl-dot:hover,
		.owl-dots .owl-dot.active{
			background-color: @theme_color;
		}

		.cart-container .cart-summary .coupon .actions-toolbar .primary .apply.primary:hover,
		.modal-footer .action-primary.action-accept:hover,
		.slider-ourmember .owl-dots .owl-dot:hover,
		.slider-ourmember .owl-dots .owl-dot.active,
		.navigation ul > li:hover > a,.navigation ul > li.active > a,
		.navigation > ul:before
		{
		  background-color: @theme_color;
		}
		.control-qty .quantity-controls:hover {color: @theme_color;}
		.block-minicart .minicart-items .product-item-details .product-item-name a:hover{
		  color: @theme_color;
		}
		.block-minicart .block-content > .actions a.viewcart{
			background-color: @theme_color;
		}
		.block-minicart .subtotal .price-container .price-wrapper:first-child .price {color: @theme_color;}

		.block-minicart .block-content > .actions a:hover{
			background-color: @theme_color !important;
		}
		.block-minicart .minicart-items .product-item-details .product.actions .action.delete::after {
			color: @theme_color !important;
		}
		.fotorama__nav-wrap--horizontal .fotorama__thumb__arr--right:hover,
		.fotorama__nav-wrap--horizontal .fotorama__thumb__arr--left:hover{
		  background-color: @theme_color;
		  border-color: @theme_color;
		}

		.fotorama-item .fotorama__nav--thumbs .fotorama__nav__frame.fotorama__active{
		  border-color: @theme_color;
		}

		.more-w .more-view{
		  color: @theme_color;
		  &:before{
		  	 color: @theme_color;
		  }
		}

		.cartpro-imageload{
			border-color: @theme_color!important;
			color: @theme_color!important;
		}

		.breadcrumbs .items .item a:hover{
			color: @theme_color!important;
		}
		
		.slidershow-home .owl-controls{
			.owl-nav > div:hover{background-color: @theme_color !important;}
		 .owl-dots .owl-dot{
		 	&:hover,&.active {
		 		border-color: @theme_color !important;
		 	}
		 }
		

		}
		.lSAction > a {
		  &:hover{
			border-color: @theme_color;
			background-color: @theme_color;
		  }
		}
		.sm-dealsproduct .deals_title_text{
			background-color: @theme_color;
		}
		.hashtags {
			h3.title_block::before{color: @theme_color;}
			div.more a{color: @theme_color;}
			ul li.item div.item-content h4:before{
				background-color: @theme_color;
			}
		}
		.rating-summary .rating-result > span::before {color: @theme_color !important;}
		#yt-totop {background-color: @theme_color !important;}
		.smcqp-actions .smcqp-btn, .smcqp-actions .smcqp-continue {background-color: @theme_color;}
		.account-nav .item.current a, .account-nav .item.current strong {border-color: @theme_color ;}
		.label-sale {background-color: @theme_color !important;}
		/* END GENERAL */

		/* LISTING */


		#price-slider .ui-slider-range{
			background-color: @theme_color;
		}

		#price-slider .ui-slider-handle{
			background-color: @theme_color;
		}

		.products-grid {
		  .item {
			.item-inner {
				
				.btn-cart{background-color: @theme_color !important;}
					 .btn-action{
						  	&.sm_quickview_handler  {
						 	  background-color: @theme_color !important;
						  	}
					   &.tocompare, &.towishlist {
						   	&:hover{
						   		 background-color: @theme_color !important;
						   	}
					   } 
					 }
				&.style1{
					.box-image .bottom-action .btn-action:hover{
						background-color: @theme_color !important;
					}
				}
				
			}
		   }
		}

		.products-list {
		  .item {
			.item-inner {
			.btn-cart{background-color: @theme_color !important;}
			 .btn-action:hover{
				  
				 background-color: @theme_color !important;
				  	
			  
			 }

			}
		  }
		}

		.toolbar{
		  .modes{
			.modes-mode{
			  &.mode-grid{
				&:hover,
				&.active{
				 background-color: @theme_color !important;
				}
			  }

			  &.mode-list{
				&:hover,
				&.active{
				  background-color: @theme_color !important;
				}
			  }
			}
		  }


		  .pages{
			.pages-items{
			  .item{
				&:hover{
				  background-color: @theme_color !important;
				 
				}

				&.current{
				  background-color: @theme_color !important;
				 
				}

			  }
			}
		  }

		}

		.products-sidebar{
			.block-title{
				strong:after{background-color: @theme_color !important;}
			}
		  .item{
			.item-inner{
			  .box-image{
				&:hover{
				  border-color: @theme_color;
				}
			  }
			}
		  }
		}

		/* END LISTING */

		/* DETAIL */

		.accordion-style .resp-accordion.resp-tab-active{
			background-color: @theme_color!important;
			border-color: @theme_color!important;
		}


		.detail-title{
		  span:before{
			background-color: @theme_color;
		  }
		}
		.content-product-detail{
			.nav-tabs > li{
				&:hover a,&.active a {
					border-color: @theme_color!important;
					color: @theme_color!important;
				} 
			}
		}
		.related-wrapper .owl-controls .owl-nav div:hover,
		.upsell-wrapper .owl-controls .owl-nav div:hover,
		.resp-vtabs .resp-tabs-list li:hover,
		.resp-vtabs .resp-tabs-list li.resp-tab-active{
		  color: @theme_color;
		}


		.related-wrapper,
		.upsell-wrapper{

		  .owl-controls{
			.owl-nav{
			  div{
				&:hover{
				  border-color: @theme_color!important;
				  background-color: @theme_color!important;
				}
			  }
			}
		  }
		}



		.product-info-main{
		  .socials-wrap ul li a:hover , .product-reviews-summary .reviews-actions a {color: @theme_color!important;}
		  .product-options-bottom,
		  .product-add-form{
			.box-tocart{
			  .fieldset{
				.actions{
				  button{
					background-color: @theme_color !important;
				  }
				}
			  }
			}
		  }

		  .product-social-links, .product-addto-links{
			.action{
				border-color: @theme_color!important;
				&:before{
				  color: @theme_color!important;
				}
			  &:hover{
				background-color:@theme_color!important;
				
			  }
			}
		  }
		}

		/* horizontal full */


		.product-image-detail{
		  .thumbs-container{
			.thumb-slider{
			  .thumb-item{
				.thumb-image{
					&:hover,
					&.thumb-active{
						border-color:@theme_color;
					}
				}
			  }
			}
		  }
		}

		/* end horizontal full */

		/* END DETAIL */

		/* TAB */

		.default-style{
		  .resp-tabs-list{
			li{
			  &:hover{
				color: @theme_color;
				border-color:@theme_color !important;
			  }

			  &.resp-tab-active,&:hover{
				color: @theme_color;
				border-color:@theme_color !important;

				&:before{
				  background-color: @theme_color;
				}
			  }
			}
		  }
		}

		.vertical-style{
		  .resp-tabs-list li {
			&.resp-tab-active{
			  &:before{
				background-color: @theme_color;
			  }
			}
		  }
		}

		.block {
			border-color: @theme_color ;
			.block-content.filter-content .filter-options-content .items li a:hover{
				&:before{border-color: @theme_color;}
				&:after{
				color: @theme_color;
				}
			}
			.block-content.filter-content .filter-options-title {border-color: @theme_color !important;}

		}
		.post-list-wrapper .post-list li.post-holder .post-text-hld .date-time .d ,
		.post-view .post-holder .post-content .date-time .d{color: @theme_color;}
		.post-view .post-holder .post-content .post-title::before {color: @theme_color;}
		/* END TAB */

		/* HEADER */
		.sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu li.sm_megamenu_actived > a,
		.sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu li:hover > a,
		.sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu li.open > a{
		  color: @theme_color !important;
		  &:before{color: @theme_color !important;}
		}

		.sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu > li.sm_megamenu_actived .sm_megamenu_actived > a{
			color: @theme_color;
		}
		.sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu > li > div {
			a:hover{color: @theme_color !important;}
			.sm_megamenu_title .title-cat:before{
				background-color: @theme_color;
			}
		}
		.title-slider-mega h2::before {background-color: @theme_color;}
		.sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu li > div {
			a:hover{color:@theme_color !important;}
			.sm_megamenu_title .sm_megamenu_head_item > .sm_megamenu_title{
				> a:before {
					background-color: @theme_color;
				}
			}

		} 
		.cms-index-index .header-style-1 .sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li:first-child > .sm_megamenu_head{
			color: @theme_color;
			&:after{
				color: @theme_color;
			}
		}
		.header-style-1 {

			.header-middle {
				
				.sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li {
					&:hover, &.sm_megamenu_actived {
						> .sm_megamenu_head, > .sm_megamenu_head:after{color: @theme_color;}
					}
					.sm_megamenu_actived > a {color: @theme_color;}
					
				}
					
				.sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li > .sm_megamenu_head:hover:after,
				.header-middle-right a:hover{color: @theme_color;}
			}
			.header-bottom .sidebar-megamenu .megamenu-content-sidebar .btn-megamenu{
				background-color: @theme_color ;
			}
			.header-bottom .minicart-header .minicart-content .cart-wrapper .minicart-wrapper .showcart {
				&:before {
					color: @theme_color;
				}
				.counter {
					.counter-number  {
						background-color: @theme_color ;
					}
					.price-minicart{
						color: @theme_color !important;
						
					}
			    }

			}
			.header-compare a:hover{
				color: @theme_color !important;
				
			}
			.header-wishlist a:hover{
				color: @theme_color !important;
			}
			
		}
		.header-style-2 {
			.sm-searchbox .sm-searchbox-content .actions .btn-searchbox {
				background-color: @theme_color !important;
			}
		
			.customer-action-hd a {
				color: @theme_color
			}
			.header-bottom {
				background-color: @theme_color !important;
			}
			.header-top .socials-wrap ul li a:hover{
				color: @theme_color !important;
			}
			.compare-wishlist a:hover{
				color: @theme_color;
				&:before{
					background-color: @theme_color;
					border-color: @theme_color ;
					color:#fff;
				}
			}
			
		}
		
		.price-box .special-price .price, .price-box .price{color: @theme_color !important;}

		
		/* END HEADER */

		/* HOME */
		.time-countdown-slide .time-wrapper .time-ranger .time-pass{
			background-color: @theme_color !important;
		}
		.time-countdown-slide .time-wrapper .stock-qty {color: @theme_color;}
		.cms-index-index.home-1-style {
				.owl-carousel .owl-controls .owl-dots .owl-dot {
					&:hover, &.active {
						background-color: @theme_color !important;
					}
				}
				.post-list li.post-holder .post-text-hld .sdsarticle-info a:hover{color: @theme_color !important;}
				.block .block-title strong::after{background-color: @theme_color !important;}
				.sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li {
					&.tab-sel, &:hover {
						color: @theme_color !important;
						&:before{
							background-color: @theme_color !important;
						}
					}
				}
				.owl-carousel  .owl-controls .owl-nav > div:hover {
					color: @theme_color !important;
				}
				.our-brands  .owl-controls .owl-nav > div:hover {
					background-color: @theme_color !important;
					border-color: @theme_color !important;
				}

		}
		.policy-home1 li.item:hover h3 a{
				color: @theme_color !important;
		}
		 .cms-index-index.home-2-style {
		 	.owl-carousel .owl-controls .owl-dots .owl-dot {
					&.active {
						background-color: @theme_color !important;
					}
			}
			.listtingtabs-list .ltabs-tabs-container .ltabs-tabs .ltabs-tab{
				&.tab-sel span, &:hover span{
					color: @theme_color !important;
					
				}
			}
			.listtingtabs-list .ltabs-items-container .products-grid .item .item-inner .box-info .bottom-action .btn-cart:hover{
						background-color: @theme_color !important;
			}
			.listtingtabs-gird .sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li{
				&.tab-sel, &:hover{
					background-color: @theme_color !important;
					border-color: @theme_color !important;
					&:after{background-color: @theme_color !important;}
				}
			}
			.block .block-title strong::after{background-color: @theme_color !important;}
			.our-brands  .owl-controls .owl-nav > div:hover {
					background-color: @theme_color !important;
					border-color: @theme_color !important;
			}
			.block.popular-search .content ul li:hover{
				background-color: @theme_color !important;
			}
		 }
		/*Home3*/

		// END DEAL SLIDE TYPE 2

		.latest-post-type2{
		  .item-post{
			.post-content{
			  .info-blog{
				.postTitle{
				  a{
					&:hover{
					  color: @theme_color;
					}
				  }
				}

				.readmore{
				  &:hover{
					background-color: @theme_color;
					border-color: @theme_color;
				  }
				}
			  }
			}
		  }

		  .owl-controls .owl-nav{
			div {
			  &:hover{
				border-color: @theme_color;
				background-color: @theme_color;
			  }
			}
		  }
		}

		.slider-brands{
		  .item{
			a{
			  &:hover{
				border-color: @theme_color;
			  }
			}
		  }

		  .owl-controls .owl-nav{
			div {
			  &:hover{
				border-color: @theme_color;
				background-color: @theme_color;
			  }
			}
		  }
		}


		.static-image-1{
		  float: right;

		  li{
			margin-bottom: 10px;

			&:last-child{
			  margin-bottom: 0;
			}
		  }
		}

		
		.top-categories-index .categories-content .info-cat h3 a:hover{
			color: @theme_color;
		}
		
		
		/* END HOME */

		/* FOOTER */

		// footer 1
		.footer-container {
			.footer-block .footer-block-title h3::before {
				color: @theme_color;
			}
			.footer-block .footer-block-content ul.links li a{
		   	&:hover{
		   		color: @theme_color;
		   		&:before{
		   			background: @theme_color;
		   		}
		   		&:after{border-color: @theme_color;}
		   	}
		   }
		   .socials-wrap ul .li-social a:hover {
		  	color: @theme_color;
		  	
		  }
		}
		.newsletter-footer .form.subscribe .action-button button{background: @theme_color !important;}
		.footer-style-2.footer-container  .before-footer {background: @theme_color;}
		.footer-style-1.footer-container {
			a:hover{color: @theme_color;}
			
			
			.categories-footer .footer-toplinks ul li a:hover {
				color: @theme_color;
		   }
		  .socials-wrap ul .li-social a:hover {
		  	color: @theme_color;
		  	
		  } 
		  
		}
		.blog-footer .post-list li.post-holder .post-text-hld .sdsarticle-info .cat  a {color: @theme_color;}
		// Footer 2 
		.footer-style-2  {
			a:hover {color: @theme_color;}
			.footer-bottom .contactinfo .content-footer {
				label .fa {color: @theme_color;}
				
			}
			.footer-copyright a {color: @theme_color ;}
			.footer-top .newsletter-footer .form.subscribe .action-button button {
				background: @theme_color !important;
			}
			.footer-top .newsletter-footer h3.title_block span {color: @theme_color;}
		}
		.footer-style-3 {
			.footer-bottom .copyright-footer a {color: @theme_color;}
			 .policy-shop-3 ul li:hover{
			 	background-color: @theme_color !important;
			 }
			  .newsletter-footer .form.subscribe .action-button button {
				background: @theme_color !important;
			}
			.newsletter-footer h3.title_block span {color: @theme_color;}
		}

		/* END FOOTER */

		/* LISTING DEALS */
		.sm-listingdeals .listingdeals-items .listingdeals-loadmore .listingdeals-loadmore-btn,
		.sm-listingdeals .listingdeals-tabs-container ul .listingdeals-tab:hover:before,
		.sm-listingdeals .listingdeals-tabs-container ul .listingdeals-tab.tab-sel:before{
			background-color: @theme_color;
		}
		/* END LISTING DEALS */

		/* LISTING EXTEND */

		.sm-listing-extend .owl-controls .owl-dots .owl-dot:hover,
		.sm-listing-extend .owl-controls .owl-dots .owl-dot.active,
		.sm-listing-extend .owl-controls .owl-nav div:hover{
			border-color: @theme_color;
		}

		/* END LISTING EXTEND */

		/* BONUS */

		.cart-container .cart.main.actions .action,
		.cart-container .cart.table-wrapper .actions-toolbar .action-edit:hover,
		.cart-container .cart.table-wrapper .actions-toolbar .action-delete:hover,
		.cart-container .checkout-methods-items .action.primary.checkout{
		  background-color: @theme_color;
		}

		/* END BONUS */

		/* PAGE */

		.pricing-title {
		  h2 {
			&:before {
			  background-color: @theme_color;
			}
		  }
		}

		.table-style-1 {
		  .table-container {
			.table-column .table-content .table-detail .button-container a {
			  &:hover{
				background-color: @theme_color;
			  }
			}
		  }
		}

		.table-style-2 {
		  .table-container {
			.table-column.column-active .table-content .table-detail .table-header {
			  color: @theme_color;
			}

			.table-column.column-active .table-content .table-detail .table-price .price{
			  color: @theme_color;
			}

			.table-column .table-content .button-container a{
				&:hover,
				&:before{
					background-color: @theme_color!important;
				}
			}

			.table-column.column-active .table-content .button-container a {
			  &:hover,
			  &:before{
				background-color: @theme_color;
			  }
			}
		  }
		}

		.table-style-4 {
		  .table-container {
			.table-column .table-content{
				.table-header,
				.button-container a {
				  background-color: @theme_color;
				}
			}
		  }
		}

		.team-style-2 {
		  .team-container {
			.team-inner .team-info {
			  background-color: @theme_color;
			}
		  }
		}

		.team-style-4 {
		  .team-container {
			.team-inner .team-info .socials li a {
			  background-color: @theme_color;
			}
		  }
		}

		.category-item .image-category .title-category h2 a:hover{
			color:@theme_color!important;
		}

		.accordion-type-1,
		.accordion-type-2,
		.accordion-type-4,
		.accordion-type-5{
			.accordion-heading .panel-title a:hover{
				color: @theme_color;
			}
		}

		.link-list {
		  li {
			a {
			  &:hover{
				color: @link_hover_color;
			  }
			}

			&.category-link-title a {
			  color: @theme_color;
			}
		  }
		}

		.testimonials-style-1 {
		  .testimonials-info {
			.name-client {
			  color: @theme_color;
			}
		  }
		}

		.events-list {
		  .item {
			.event-info {
			  .bottom-info a{
				color: @theme_color;
			  }
			}

			.event-info .event-title h2 a {
			  &:hover{
				color: @link_hover_color;
			  }
			}

		  }
		}

		.w-newsletter {
		  .newsletter-info {
			.form-newsletter-popup .action-newsletter button {
			  background-color: @theme_color;
			}
		  }
		}

		.socials-popup {
		  li {
			a:hover {
			  background-color: @theme_color;
			  border-color: @theme_color;
			}
		  }
		}

		/* END PAGE */

		// RESPONSIVE

		@media (min-width: 1200px) {
		  .header-style-1 .header-top .header-top-links .toplinks-wrapper .header.links li.myaccount-link a {
			background-color: @theme_color;
		  }

		 
		}

		@media (min-width: 992px) and (max-width: 1199px) {

		}

		@media (min-width: 768px) and (max-width: 991px) {
			.header-style-1 .header-middle .middle-right-content .sm-searchbox .sm-searchbox-content .actions .btn-searchbox{
				background-color: @theme_color!important;
			}

			
		}

		@media (max-width: 768px) {
			
			

		}

		@media (max-width: 480px) {

		}
	";
?>