<div class="service-title">
	<div class="container">
        <div class="row">
            <div class="col-md-12">
				<h2>Business News</h2>
        	</div>
        </div>
    </div>
</div>
<div class="service-carousel-section">
	<div class="container">
        <div class="row">
        	<div class="col-md-12">
            	<div class="srequest-block">
                	<div id="service_carousel" class="owl-carousel owl-theme">
                        
                        <div class="item">
                            <div class="item-block">
                            	<p>
                                Nafisa Bakkar Tesco's use of a Muslim family in their Christmas ad has backfired
                                </p>
                                <span class="date">16 Nov, 2017</span>
                            </div>
                        </div>
                        <div class="item">
                            <div class="item-block">
                            	<p>
                                Nafisa Bakkar Tesco's use of a Muslim family in their Christmas ad has backfired
                                </p>
                                <span class="date">16 Nov, 2017</span>
                            </div>
                        </div>
                        <div class="item">
                            <div class="item-block">
                            	<p>
                                Nafisa Bakkar Tesco's use of a Muslim family in their Christmas ad has backfired
                                </p>
                                <span class="date">16 Nov, 2017</span>
                            </div>
                        </div>
                        <div class="item">
                            <div class="item-block">
                            	<p>
                                Nafisa Bakkar Tesco's use of a Muslim family in their Christmas ad has backfired
                                </p>
                                <span class="date">16 Nov, 2017</span>
                            </div>
                        </div>
                        
					</div>
                    
                </div>
            </div>
        </div>
	</div>
</div>

<div class="service-block-section">
	<div class="container">
        <div class="row">
        	<div class="col-md-12">
            	<div class="srequest-block">
                	<div id="service-block">
                    	<ul>
                        	<li>
                            	<figcaption>Business Services –<br>Education,</figcaption>
                                <figure><img src="<?php echo $this->getViewFileUrl('images/ser1.jpg') ?>" width="372" height="215"></figure>
                            </li>
                            <li>
                            	<figcaption><img src="<?php echo $this->getViewFileUrl('images/ser-icon2.png') ?>" width="87" height="76"><br>Recruitment Agency</figcaption>
                                <figure><img src="<?php echo $this->getViewFileUrl('images/ser2.jpg') ?>" width="372" height="215"></figure>
                            </li>
                            <li>
                            	<figcaption>Trade Finance</figcaption>
                                <figure><img src="<?php echo $this->getViewFileUrl('images/ser3.jpg') ?>" width="372" height="215"></figure>
                            </li>
                            <li>
                            	<figcaption>Secretariat Services</figcaption>
                                <figure><img src="<?php echo $this->getViewFileUrl('images/ser4.jpg') ?>" width="372" height="215"></figure>
                            </li>
                            <li>
                            	<figcaption><img src="<?php echo $this->getViewFileUrl('images/ser-icon5.png') ?>" width="156" height="147"><br>Halal Certification Consultancy</figcaption>
                                <figure><img src="<?php echo $this->getViewFileUrl('images/ser5.jpg') ?>" width="372" height="215"></figure>
                            </li>
                            <li>
                            	<figcaption>Consulting</figcaption>
                                <figure><img src="<?php echo $this->getViewFileUrl('images/ser6.jpg') ?>" width="372" height="215"></figure>
                            </li>
                            <li>
                            	<figcaption>Halal Certification Bodies</figcaption>
                                <figure><img src="<?php echo $this->getViewFileUrl('images/ser7.jpg') ?>" width="372" height="215"></figure>
                            </li>
                            
                        </ul>
                    </div>
                </div>
            </div>
        </div>
	</div>
</div>
<script type="text/javascript">
	require([
		'jquery',
		'owlcarousel'
	], function ($) {
		///////
		$('.owl-carousel').owlCarousel({
			loop:true,
			margin:30,
			responsiveClass:true,
			nav:false,
			responsive:{
				0:{
					items:1,
				},
				600:{
					items:2,
				},
				1000:{
					items:3,
				}
			}
		})
		////// 
	});
</script> 
