<!-- 
<div class="our-brands">
	<h2>Brand Zone</h2>
    <div class="inner-brands owl-carousel">
    	<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$catId = 16; // Parent Category ID
	$subcategory = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
	$subcats = $subcategory->getChildrenCategories();
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	?>
	<?php
	foreach ($subcats as $subcat) {
	$_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
	$_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
	$subcaturl = $subcat->getUrl();
	$_imgHtml = '';
	if ($_imgUrl = $_category->getImageUrl()) {
	$_imgHtml = '<img src="' . $_imgUrl . '" />';
	$_imgHtml = $_outputhelper->categoryAttribute($_category, $_imgHtml, 'image');

} ?>
        <div class="item"><a href="<?php echo $subcaturl ?>"><img class="img" src="<?php echo $_category->getImageUrl() ?>" height="100px" width="100px" /></a></div>
        <?php } ?>
    </div>
</div>

<div class="our-brands">
	<h2>Featured Sellers</h2>
    <div class="inner-brands owl-carousel">
        <div class="item"><a href="#"><img class="img" src="<?php echo $this->getViewFileUrl('images/bp1.png') ?>" /></a></div>
        <div class="item"><a href="#"><img class="img" src="<?php echo $this->getViewFileUrl('images/bp2.png') ?>" /></a></div>
        <div class="item"><a href="#"><img class="img" src="<?php echo $this->getViewFileUrl('images/bp3.png') ?>" /></a></div>
        <div class="item"><a href="#"><img class="img" src="<?php echo $this->getViewFileUrl('images/bp4.png') ?>" /></a></div>
        <div class="item"><a href="#"><img class="img" src="<?php echo $this->getViewFileUrl('images/bp5.png') ?>" /></a></div>
        <div class="item"><a href="#"><img class="img" src="<?php echo $this->getViewFileUrl('images/bp6.png') ?>" /></a></div>
        <div class="item"><a href="#"><img class="img" src="<?php echo $this->getViewFileUrl('images/bp7.png') ?>" /></a></div>
        <div class="item"><a href="#"><img class="img" src="<?php echo $this->getViewFileUrl('images/bp1.png') ?>" /></a></div>
    </div>
</div>

<div class="our-brands">
	<h2>Certification Bodies</h2>
    <div class="inner-brands owl-carousel">
        <div class="item"><a href="#"><img class="img" src="<?php echo $this->getViewFileUrl('images/bp1.png') ?>" /></a></div>
        <div class="item"><a href="#"><img class="img" src="<?php echo $this->getViewFileUrl('images/bp2.png') ?>" /></a></div>
        <div class="item"><a href="#"><img class="img" src="<?php echo $this->getViewFileUrl('images/bp3.png') ?>" /></a></div>
        <div class="item"><a href="#"><img class="img" src="<?php echo $this->getViewFileUrl('images/bp4.png') ?>" /></a></div>
        <div class="item"><a href="#"><img class="img" src="<?php echo $this->getViewFileUrl('images/bp5.png') ?>" /></a></div>
        <div class="item"><a href="#"><img class="img" src="<?php echo $this->getViewFileUrl('images/bp6.png') ?>" /></a></div>
        <div class="item"><a href="#"><img class="img" src="<?php echo $this->getViewFileUrl('images/bp7.png') ?>" /></a></div>
        <div class="item"><a href="#"><img class="img" src="<?php echo $this->getViewFileUrl('images/bp1.png') ?>" /></a></div>
    </div>
</div>

<script type="text/javascript">
			require([
				'jquery',
				'owlcarousel'
			], function ($) {
				$(".our-brands .inner-brands").owlCarousel({				
					nav: true,
					dots:false,	
                    loop:false,
                    margin:0,
					responsive: {
						0: {
							items:2
						},
						480: {
							items:3
						},
						768: {
							items:4
						},
						991: {
							items:5
						},						
						1200: {
							items:6
						},
                        1368: {
							items:7
						},
						1900: {
							items:8
						}
					}
				});	  
			});
		
// ]]></script> -->