<style>
body{
	margin:0;
	padding:0;
}
.fulluc-img{
	width:100%;
	height:auto;
	display:block;
	position:relative;
}
.fulluc-img > img{
	width:100%;
	height:auto;
	display:block;
}
.fulluc-img ul{
	width:auto;
	height:auto;
	display:inline-flex;
	position:absolute;
	bottom:38px;
	right:82px;
	z-index:5;
	padding:0;
	margin:0;
	list-style:none;
}
.fulluc-img ul li{
	width:38px;
	height:auto;
	display:inline-block;
	margin:0 20px 0 0;
}
.fulluc-img ul li:last-child{
	margin:0;
	padding:0;
}
.fulluc-img ul li img{
	width:100%;
	height:auto;
	display:block;
}
.fulluc-img ul li a{
	width:100%;
	height:auto;
	display:block;
	transition:all 0.3s;
	-moz-transition:all 0.3s;
	-webkit-transition:all 0.3s;
	-o-transition:all 0.3s;
}
.fulluc-img ul li a:hover{
	opacity:0.6;
}
body.cms-page-under-construction p,
body.cms-page-under-construction .breadcrumbs,
body.cms-page-under-construction .page-footer,
body.cms-page-under-construction .header-container.header-style-1{
	display:none !important;
}
body.cms-page-under-construction .page-main {
	padding:  0;
	min-height: inherit;
}
body.cms-page-under-construction .container {
	width: 100%;
	max-width: inherit;
}
body.cms-page-under-construction .col-lg-12.col-md-12{
	padding:0;
}
</style>
<div class="fulluc-img">
	<ul>
    	<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/us1.png') ?>" width="55" height="59"></a></li>
        <li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/us2.png') ?>" width="55" height="59"></a></li>
        <li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/us3.png') ?>" width="55" height="59"></a></li>
    </ul>
	<img src="<?php echo $this->getViewFileUrl('images/under.jpg') ?>" width="1800" height="1225">
</div>