<div id="plan-container">
					<div class="plan-tittle">
                        <h2>Choose the right plan for your business</h2>
                        <!-- <p>Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...</p> -->
                    </div>
                    <!--<div class="plan-pic"><img src="" width="1280" height="904"></div>-->
                    <div class="container">
                        <div class="row">

                          	<div class="col-xs-12 col-sm-12 col-md-12">
                            	<div class="plans-outer-table">
                                    <div class="plans-table">
                                        <div class="columns-txt">
                                          <ul class="price">
                                            <li class="header">Plan<br>Features</li>
                                            <li>Product Listing</li>
                                            <li>Online Chat with Bulk/Wholesale customer</li>
                                            <li>Listing of Products</li>
                                            <li>Order Tracking</li>
                                            <li>Events / Trades Expo Updates</li>
                                            <li>Advertising their Products in different Search page</li>
                                            <li>Directory Services - Additional services</li>
                                            <li>Featured Seller listing</li>
                                            <li>Add in Community / Network</li>
                                            <li>World wide selling leads</li>
                                            <li>Discount in Transaction Fee</li>
                                            <li>Verified Seller Tag by HGH</li>
                                            <li class="ul-footer"></li>
                                          </ul>
                                        </div>
                                        <div class="columns">
                                          <ul class="price">
                                            <li class="header"><span>Basic</span></li>
                                            <li style="min-height: 66px;"><span>20 Max</span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 91px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-not.png" width="16" height="21"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-not.png" width="16" height="21"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-not.png" width="16" height="21"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-not.png" width="16" height="21"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-not.png" width="16" height="21"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-not.png" width="16" height="21"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-not.png" width="16" height="21"></span></li>
                                            <li class="ul-footer" style="min-height: 100px;"><a href="#" class="button">BUY NOW</a></li>
                                          </ul>
                                        </div>
                                        <div class="columns">
                                          <ul class="price">
                                            <li class="header"><span>Classic</span></li>
                                            <li style="min-height: 66px;"><span>50 Max</span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 91px;"><span>2 Pages</span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-not.png" width="16" height="21"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-not.png" width="16" height="21"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li class="ul-footer" style="min-height: 100px;"><a href="#" class="button">BUY NOW</a></li>
                                          </ul>
                                        </div>

                                        <div class="columns">
                                          <ul class="price">
                                            <li class="header"><span>Privilege</span></li>
                                            <li style="min-height: 66px;"><span>50+</span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 91px;"><span>5 Pages</span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li style="min-height: 66px;"><span><img src="http://halalglobalhub.com/pub/static/version1518853663/frontend/Sm/emarket/en_US/images/plan-tick.png" width="14" height="11"></span></li>
                                            <li class="ul-footer" style="min-height: 100px;"><a href="#" class="button">BUY NOW</a></li>
                                          </ul>
                                        </div>

                                    </div>
                                </div>
							</div>


                        </div>
                    </div>
                    <!--<div class="container">
                        <div class="row">

                          <div class="col-xs-12 col-sm-12 col-md-12">

                              dddd
                            </div>


                        </div>
                    </div>-->

               </div>